### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [aswild/samd21#1]
In the file "samd21/lib/MPR121/MPR121.cpp" you may remove the two "`while (!i2c.available());`" after a Wire.requestFrom().
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by aswild** [comment]
Hey @Koepel, thanks for this! I'll push a fix.

I think you also win the honor of First Person Who Opened an Issue on a Personal Project for me :)  
Out of curiosity, how'd you find my repo?

**Comment by Koepel** [comment]
Google and the search function of Github: [Are you using spider bot to scan Arduino libraries which misused the Wire library?](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/issues/1)

**Comment by aswild** [comment]
aha, nice

**Comment by buccaneer-jak** [comment]
Excellent explanations but I want to mention that I had problems when reading from I2C. My first 2 Wire.requestFrom() would work and the following 2 had corrupt bits. If I commented out the first 2 Wire.requestFrom() then the following 2 would return valid data.

Then I came across an explanation in StackExchange that said I needed a delay(1) before requestFrom(), although it looks like perhaps only 1 clock cycle delay is needed and so could use 
delayMicroseconds() say 20-50 microseconds (I need to calculate clock cycle time)

This is my working code with a delay(1). Without the delay as I mentioned I get corrupt data and a lot of headaches. And yes I could use Wire.requestFrom(I2C_ADDRESS, 2); but for checking I was only returning 1 byte at a time. 

Perhaps this error is because I am requesting from different registry areas (VOUT_L) then (MFR_ID) between Wire.requestFrom() as the registry's are not concurrent?

So as you have the best explanation so far perhaps you might consider adding that a delay() or a timer interrupt might be needed before Wire.requestFrom().

  Wire.beginTransmission(I2C_ADDRESS);
  Wire.write(VOUT_L);
  Wire.endTransmission(false);

  delay(1);
  Wire.requestFrom(I2C_ADDRESS, 1);
  LSB_regByte = Wire.read();
  Wire.requestFrom(I2C_ADDRESS, 1);
  MSB_regByte = Wire.read();

  Wire.beginTransmission(I2C_ADDRESS);
  Wire.write(MFR_ID);
  Wire.endTransmission();
  
  delay(1);
  Wire.requestFrom(I2C_ADDRESS, 1);
  regByte = Wire.read();
  Wire.requestFrom(I2C_ADDRESS, 1);
  regByte2 = Wire.read();
